name: Trunk Check
on:
  workflow_dispatch:
    inputs:
      client_payload:
        description: Deprecated
      clientPayload:
        description: Passed through to trunk-io/trunk-action@v1
        required: true
      githubToken:
        description: Deprecated
      trunkToken:
        description: Deprecated

permissions: {}

jobs:
  check:
    name: ${{ fromJSON(inputs.clientPayload).checkJobName }}
    runs-on: ${{ fromJSON(inputs.clientPayload).checkJobRunsOn }}
    concurrency:
      group: ${{ fromJSON(inputs.clientPayload).concurrencyGroup }}
      cancel-in-progress: true

    steps:
      - name: Trunk Check
        uses: trunk-io/trunk-action@v1
        with:
          github-event-path: ${{ github.event_path }}
