name: Trunk Check
run-name: ${{ fromJSON(inputs.payload).checkWorkflowRunName }}
on:
  workflow_dispatch:
    inputs:
      payload:
        description: For invocation by Trunk Check
        required: false

permissions:
  contents: read

jobs:
  check:
    strategy:
      fail-fast: ${{ fromJSON(inputs.payload).checkJobMatrixFailFast }}
      matrix:
        include: ${{ fromJSON(inputs.payload).checkJobMatrix }}

    name: ${{ matrix.name }}
    runs-on: ${{ matrix.runsOn }}
    concurrency:
      group: ${{ matrix.concurrencyGroup }}
      cancel-in-progress: true

    steps:
      - name: Trunk Check
        uses: trunk-io/trunk-action@v1
        with:
          check-mode: payload
